Adding Horovod
faasm/faasm-cpython pull request #1
Opened 2020-10-05 09:07 UTC by Shillaker

2020-10-07 16:58 UTC, csegarragonz requested changes

2020-10-07 16:58 UTC, csegarragonz commented on README.md
>  for use in [Faasm](https://github.com/lsds/faasm).
Update to `faasm/faasm`

2020-10-07 16:58 UTC, csegarragonz commented on README.md
> +inv libs.install <module_name>
I am not sure, but why wouldn't this be:
```bash
inv libs.install --name <module_name>
```

2020-10-07 16:58 UTC, csegarragonz commented on README.md
> +inv libs.install --name=horovod
Again, does it equally work with a space (`--name mxnet`) than with an equal (`--name=mxnet`). Most likely yes, but just double-checking.

2020-10-07 16:58 UTC, csegarragonz commented on bin/install_build_python.sh
> +
Do we like empty newlines at the end of a file? Do we enforce something (on a relaxed, not linter-related manner)? I'd personally try to avoid them.

2020-10-07 16:58 UTC, csegarragonz commented on tasks/libs.py
> +CMAKE_TOOLCHAIN_FILE = (
Couldn't we use here the `FAASM_TOOLCHAIN_FILE` defined in `tasks/env.py`?

2020-10-09 07:36 UTC, Shillaker commented on bin/install_build_python.sh
> +
Given the amount of time we spent on the C/C++ newline checker I'm reluctant to discuss this any more. If we can find something to enforce bash style automatically (including EOF newlines), then great. If not, we'll have to remain agnostic about newlines as it's too hard to police and there is no consensus on what's right (e.g. I actually prefer them :man_shrugging:)

2020-10-09 07:40 UTC, Shillaker commented on libffi.imports
> +ffi_call
This will make more sense once this repo is moved to `faasm-toolchain` where this will live in the `sysroot-extras` folder along with the other `.imports` files

2020-10-09 09:45 UTC, csegarragonz commented
LGTM

2020-10-09 09:57 UTC, csegarragonz approved these changes

2020-10-09 09:57 UTC, csegarragonz commented on tasks/libs.py
> +# Modified libs
Thinking out loud here, but afaict, we claim we support installing certain libraries. I assume at this moment this is true, but is there any testing mechanism in place to check that this is _actually_ true at any given moment in time? I guess this follows from yesterday's discussion, and would help us noticing when something breaks.

2020-10-09 09:57 UTC, csegarragonz commented
LGTM

Just wondering about the regression-testing side of things.

2020-10-09 11:39 UTC, Shillaker commented on tasks/libs.py
> +# Modified libs
"Supported" in the context of this repo just means that they successfully compile to WebAssembly. We don't claim that they will actually be usable anywhere. I guess we could put some CI here but it seems like overkill.

To test whether modules are actually usable in Faasm, we have a couple of test functions in the main repo (e.g. `numpy_test` and `lang_test`) which check the essential bits of Python functionality. Most of the libraries installed in here are related to performance testing, so aren't worth enforcing that strongly. Once MXNet and Horovod are "officially" supported I'll add some test functions for them.

2020-10-09 11:40 UTC, merged